os:
  - linux
  - osx

node_js:
  - "10"
  - "8"
  - "6"
  - "iojs"

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0"
  - "export PATH=\"$HOME/.yarn/bin:$PATH\""

install:
  - "yarn run setup"

script:
  - yarn run build

cache:
  yarn: false
