language: node_js

os:
  - linux
  - osx

env:
  - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
  - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist

node_js:
  - "10"
  - "8"
  - "6"
  - "7"
  - "iojs"

matrix:
  allow_failures:
    - node_js: "iojs"
    - env:
      - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0"
  - "export PATH=\"$HOME/.yarn/bin:$PATH\""

install:
  - "yarn run setup"

script:
  - yarn run build
  - yarn run test

cache:
  yarn: false
